# Generated by Django 5.1.3 on 2024-11-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('payment_method', models.CharField(blank=True, choices=[('Card', 'Card'), ('UPI', 'UPI'), ('Cash', 'Cash')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
